### PR TITLE
Fix Get-vRNIApplication for 6.7.0

### LINKED ISSUE #32: Get-vRNIApplication returns only 100 results on vRNI 6.7.0
When running Get-vRNIApplication in PowerVRNI 6.51.185 (from PSGallery) against vRNI 6.7.0, only 100 applications are returned. 

In 2846a57660b8720b4bf6b98e135f545196f0f74a the page size for the call to /api/ni/groups/applications/fetch was changed from 2500 to 100. There is a while loop at the end of the function definition that looks like it should keep retrieving 100 apps at a time until there are none left, but it stops after 1 iteration. Since we have 669 applications, we didn't need to loop previously. 

It seems like at least one person might have run into the same problem: https://github.com/PowervRNI/powervrni/issues/30#issuecomment-1281705438

Thanks in advance.

### PR DESCRIPTION
**Pull request by skruje**
Fixes #32 by modifying Get-vRNIApplication to retrieve applications 100 at a time on 6.7.0.

### CODE REVIEW

**Comment by smitmartijn** [comment]
Hi @skruje - thanks for your PR. After looking at the code, that's indeed a 🐛  - weird that it hasn't come up yet. Looking at your PR code, I think it might be easier and less redundant if these lines were just removed, from line 2378:

```
      $applications = Invoke-vRNIRestMethod @listParams
      $applications.results
      return
```

The continuation of the page list with cursor is already present below that block and should take care of the loop to retrieve more data. The only addition required is that getting the app details (`foreach ($app in $applicationResponse.results) {`) isn't necessary, because the app details are already in the 1.1.0+ API output. 

Does that make sense? Can you try it?

**Comment by skruje** [comment]
That makes sense. I'll write it up and update my branch for your review.

**Comment by skruje** [comment]
@smitmartijn can you please have another look?

**Comment by smitmartijn** [comment]
LGTM, thanks!

**Pull request merged**
